all:
  children:
    managed_nodes:
      hosts:
        ansible-target:
          ansible_host: localhost
          ansible_port: 2222
          ansible_user: root
          ansible_ssh_private_key_file: docker/ssh/id_rsa
