---
# roles/dotfiles/tasks/main.yml
- name: Ensure .bashrc exists
  file:
    path: "/home/traum/.bashrc"
    state: touch
    mode: '0644'
    owner: "traum"
    group: "traum"

# Add common aliases first
- name: Add common aliases
  blockinfile:
    path: "/home/traum/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED COMMON ALIASES"
    block: |
      {% for item in shell_aliases_common %}
      alias {{ item.alias }}='{{ item.command }}'
      {% endfor %}

# Add Arch-specific aliases
- name: Add Arch Linux aliases
  blockinfile:
    path: "/home/traum/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED ARCH ALIASES"
    block: |
      {% for item in shell_aliases_arch %}
      alias {{ item.alias }}='{{ item.command }}'
      {% endfor %}
  when: ansible_facts['os_family'] == "Archlinux"

# Add Ubuntu-specific aliases
- name: Add Ubuntu aliases
  blockinfile:
    path: "/home/traum/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED UBUNTU ALIASES"
    block: |
      {% for item in shell_aliases_ubuntu %}
      alias {{ item.alias }}='{{ item.command }}'
      {% endfor %}
  when: ansible_facts['os_family'] == "Debian"
