FROM ubuntu:22.04

# Install required packages
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    openssh-server \
    python3 \
    sudo \
    zsh \
    && rm -rf /var/lib/apt/lists/*

# SSH Server setup
RUN mkdir /var/run/sshd
RUN echo 'PermitRootLogin prohibit-password' >> /etc/ssh/sshd_config
RUN sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config

# Create required directories
RUN mkdir -p /root/.ssh

# Expose SSH port
EXPOSE 22

# Start SSH server
CMD ["/usr/sbin/sshd", "-D"]
