version: '3.8'
services:
  arch:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "2222:22"
    volumes:
      - ./ssh/authorized_keys:/root/.ssh/authorized_keys
      - ~/docker-persist/arch:/home/traum/persist
    hostname: ansible-arch
    restart: unless-stopped

  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile.ubuntu
    ports:
      - "2223:22"
    volumes:
      - ./ssh/authorized_keys:/root/.ssh/authorized_keys
      - ~/docker-persist/ubuntu:/home/traum/persist
    hostname: ansible-ubuntu
    restart: unless-stopped

  rhel:
    build:
      context: .
      dockerfile: Dockerfile.rhel
    ports:
      - "2224:22"
    volumes:
      - ./ssh/authorized_keys:/root/.ssh/authorized_keys
      - ~/docker-persist/rhel:/home/traum/persist
    hostname: ansible-rhel
    restart: unless-stopped
